spring:
  # ========= DATABASE MYSQL =========== #
  datasource:
    url: jdbc:mysql://localhost:3306/tp_academy_db_jpa?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: tp_academy_user_jpa
    password: tp_academy_password_jpa
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect

